### PR TITLE
version-bump

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@dougalsutherland : Is it a noarch?

**Comment by djsutherland** [comment]
@sannykr Looks like it. The way to test is basically:

- Make sure the recipe doesn't have anything that depends on the platform/Python version.
- Check that setup.py doesn't have any `ext_modules`, other ways to compile anything, or any code depending on the Python version / platform.

**Comment by sannykr** [comment]
@dougalsutherland : When I used noarch and rerendered, it worked fine. But I can see something different on conda-forge. 
https://anaconda.org/conda-forge/django-anymail/files?version=1.0

**Comment by djsutherland** [comment]
@sannykr I'm not seeing it being `noarch` [in `master`](https://github.com/conda-forge/django-anymail-feedstock/blob/b380394d76514ec4da3f60c8577e5e2ca57c5ce0/recipe/meta.yaml#L14-L16) or in this PR. Looks like you forgot to push or something?

**Comment by djsutherland** [comment]
Oh, I think you committed the rerendering but not the `noarch: python` line.

**Comment by sannykr** [comment]
Thanks. First I added noarch, and then re-rendered. But I forgot to run git add before commiting the changes, so I missed the changes that I made in meta.yaml file.

**Comment by djsutherland** [comment]
Yep. You should probably commit the `noarch: python` version and also bump the build number at the same time, to avoid the problem I literally just got with another package:  https://github.com/conda-forge/tqdm-feedstock/pull/16. :)

**Pull request merged**
